name: Lint Code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8 main_app